- name: Include vars in variables.yaml
  ansible.builtin.include_vars:
    file: variables.yaml
- name: Packager Update & Upgrade
  apt:
    update_cache: yes
    upgrade: "yes"
- name: Installing Tooling packages
  ansible.builtin.package:
    name:
      - tmux
      - zsh
      - nfs-common
      - net-tools
    state: present
