- name: Basic Server Configuration
  hosts: "*"
  become: yes
  tasks:
    - name: Include vars in variables.yaml
      ansible.builtin.include_vars:
        file: variables.yaml
    - name: Packager Update & Upgrade
      apt:
        update_cache: yes
        upgrade: 'yes'
    - name: Installing Tmux
      ansible.builtin.package:
        name:
         - tmux
        state: present
    - name: Setup drifter user
      ansible.builtin.user:
        name: '{{ drifter_user }}'
        groups: "sudo"
        append: true
    - name: Allow passwordless sudo for docker user
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^{{ drifter_user }}'
        line: '{{ drifter_user }} ALL=(ALL) NOPASSWD:ALL'
        validate: '/usr/sbin/visudo -cf %s'
    - name: Set authorized key from file
      ansible.posix.authorized_key:
        user: '{{ drifter_user }}'
        state: present
        key: "{{ lookup ('file', '{{ drifter_user_pub_key }}')}}"