- name: Setting Up Docker Swarm For RaspberryPiOs (Assuming Docker is installed)
  hosts: "rpi5"
  become: yes
  tasks:
  - name: Include vars in variables.yaml
    ansible.builtin.include_vars:
      file: variables.yaml
  - name: Packager Update & Upgrade
    apt:
      update_cache: yes
      upgrade: 'yes'
