- name: Basic Server Configuration
  hosts: all
  become: true
  roles:
    - tools
    - drifter

- name: QEMU Agent on VM
  hosts: proxmox-vms
  become: true
  roles:
    - qemu

- name: Installing Python packages
  hosts: workstation
  become: true
  roles:
    - python-packages
